trajectory_planner:
  ros__parameters:
    odom_topic: "/odom"
    map_topic: "/map"
    scan_topic: "/scan"
    initial_pose_topic: "/initialpose"
yeet:
  ros__parameters:
    odom_topic: "/odom"
    drive_topic: "/drive"
