trajectory_planner:
  ros__parameters:
    odom_topic: "/pf/pose/odom"
    map_topic: "/map"
    scan_topic: "/scan"
    initial_pose_topic: "/initialpose"
    clicked_point_topic: "/clicked_point"
yeet:
  ros__parameters:
    odom_topic: "/pf/pose/odom"
    drive_topic: "/vesc/input/navigation"
